// angular2-free/3-init-routes-and-assets/src/app/modules/login/login.component.ts
import { Component, ViewEncapsulation, OnInit, OnDestroy, Inject } from '@angular/core';
import { Router } from '@angular/router';
import 'rxjs/Rx';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit, OnDestroy {
  username: string = '';
  password: string = '';

  constructor() {
  }

  ngOnInit() {
    $('body').addClass('login');
  }

  // 登录事件
  onSubmit() {
    if (!this.username || !this.password) {
      alert('账户和密码不能为空');
      return;
    }
    // this.router.navigate(['/home']);
  }

  ngOnDestroy(){
    $('body').removeClass('login');
  }
}
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form (ngSubmit)="onSubmit">
                    <h1>管理系统</h1>
                    <div>
                        <input type="text" class="form-control" placeholder="用户名" [(ngModel)]="username" name="username" required autofocus />
                    </div>
                    <div>
                        <input type="password" class="form-control" placeholder="密码" [(ngModel)]="password" name="password" required />
                    </div>
                    <div>
                        <button class="btn btn-default submit" type="submit">登录</button>
                    </div>

                    <div class="clearfix"></div>
                </form>
            </section>
        </div>

    </div>
</div>

// react-redux-notes/6-create-sidebar/app/routes/login/Login.jsx
import React, { Component, PropTypes } from 'react'

export class Login extends Component {
	render() {
		return (
			<div>
				<a className="hiddenanchor" id="signup"></a>
				<a className="hiddenanchor" id="signin"></a>

				<div className="login_wrapper">
					<div className="animate form login_form">
						<section className="login_content">
							<form onKeyPress={(e) => { if (e.key === 'Enter') { this.loginSubmit(e) } } }>
								<h1>管理系统</h1>
								<div>
									<input type="text" className="form-control" placeholder="用户名" ref="username" required />
								</div>
								<div>
									<input type="password" className="form-control" placeholder="密码" ref="password" required />
								</div>
								<div>
									<a className="btn btn-default submit" onClick={(e) => { this.loginSubmit(e) } }>登录</a>
								</div>

								<div className="clearfix"></div>

							</form>
						</section>
					</div>

				</div>
			</div>
		)
	}

	loginSubmit() {
		const username = this.refs.username.value.trim()
		const password = this.refs.password.value.trim()
		// console.log(JSON.stringify({username,password}).toString());
		if (username === undefined || password === undefined) {
			Notify({
				title: '账户或密码不能为空',
				type: 'error'
			})
			return
		}
		sessionStorage.setItem('username', username)
		this.context.router.push('/home')
	}

	componentDidMount() {
		$('body').attr('class', 'login')
	}
}

Login.contextTypes = {
	router: React.PropTypes.object
}

export default Login
