// react-redux-notes/6-create-sidebar/app/routes/home/components/Top.jsx
import React, { Component, PropTypes } from 'react'
import { toggleSidebar, setUserName } from '../../../actions/commonActions.js'


export class Top extends Component {
    render() {
        const { dispatch, isSidebarShown } = this.props
        return (
            <div className="top_nav">
                <div className="nav_menu">
                    <nav>
                        <div className="nav toggle">
                            <a id="menu_toggle" onClick={() => { dispatch(toggleSidebar(isSidebarShown() ? false : true)); $('body').toggleClass('nav-md nav-sm') } }><i className="fa fa-bars"></i></a>
                        </div>

                        <ul className="nav navbar-nav navbar-right">
                            <li className="">
                                <a href="javascript:;" className="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    用户
                                        <span className=" fa fa-angle-down"></span>
                                </a>
                                <ul className="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;">设置</a></li>
                                    <li><a onClick={() =>{this.logout()}}><i className="fa fa-sign-out pull-right"></i>退出</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        )
    }
    logout(){
        sessionStorage.removeItem('username')
		this.context.router.push('/login')
    }
}

Top.contextTypes = {
	router: React.PropTypes.object
}

export default Top

// vue2-notes/9-watch-router/src/components/Top.vue
<template>
	<!-- top navigation -->
	<div class="top_nav">
		<div class="nav_menu">
			<nav>
				<div class="nav toggle">
					<!--这里添加点击事件，用来触发Sidebar的展开和收起-->
					<a id="menu_toggle" v-on:click="sidebarToggleClick"><i class="fa fa-bars"></i></a>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
							用户
							<span class=" fa fa-angle-down"></span>
						</a>
						<ul class="dropdown-menu dropdown-usermenu pull-right">
							<li><a href="javascript:;">设置</a></li>
							<li><router-link to="/login"><i class="fa fa-sign-out pull-right"></i>退出</router-link></li>
						</ul>
					</li>
				</ul>
			</nav>
		</div>
	</div>
	<!-- /top navigation -->
</template>


<script>
    export default {
        // 在 `methods` 对象中定义方法
        methods: {
            // 点击事件
            sidebarToggleClick() {
                // 使用$emit触发自定义事件SidebarToggleClick
                this.$emit('SidebarToggleClick');
            }
        }
    }
</script>
