// react-redux-notes/3-use-router-login/app/components/login.jsx
import React from 'react'; //导入react组件

const Login = React.createClass({
	render() {
		return (
			<div>
				<a className="hiddenanchor" id="signup"></a>
				<a className="hiddenanchor" id="signin"></a>

				<div className="login_wrapper">
					<div className="animate form login_form">
						<section className="login_content">
							<form>
								<h1>管理系统</h1>
								<div>
									<input type="text" className="form-control" placeholder="用户名" ref="username" required />
								</div>
								<div>
									<input type="password" className="form-control" placeholder="密码" ref="password" required />
								</div>
								<div>
									<a className="btn btn-default submit" href="javascript:;" onClick={this.loginSubmit}>登录</a>
								</div>

								<div className="clearfix"></div>

							</form>
						</section>
					</div>

				</div>
			</div>
		);
	},
	getInitialState() {
		return {//设置默认属性
			username: '',
			password: ''
		};
	},
	contextTypes: {
		router: React.PropTypes.object
	},
	loginSubmit() {
		this.context.router.push('/index'); //使用this.content进行跳转
	},
	componentDidMount() {
		sessionStorage.removeItem('username')
		$('body').attr('class', 'login')
	}
});

module.exports = Login;

// vue2-notes/9-watch-router/src/Login.vue
<template>
	<transition name="fade">
		<div>
			<a class="hiddenanchor" id="signup"></a>
			<a class="hiddenanchor" id="signin"></a>
			<div class="login_wrapper">
				<div class="animate form login_form">
					<section class="login_content">
						<form>
							<h1>管理系统</h1>
							<div>
								<input type="text" class="form-control" placeholder="用户名" v-model="username" required="" />
							</div>
							<div>
								<input type="password" class="form-control" placeholder="密码" v-model="password" required="" />
							</div>
							<div class="alert alert-danger alert-dismissible fade in" role="alert" v-show="error.shown">
								<strong>错误：</strong> {{error.text}}
							</div>
							<div>
								<a class="btn btn-default submit" href="javascript:;" v-on:click="login">登录</a>
							</div>

							<div class="clearfix"></div>
							<div>
								<h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
								<p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
							</div>
						</form>
					</section>
				</div>
			</div>
		</div>
	</transition>
</template>

<script>
    export default {
        name: 'Login',
        data() {
            return {
                username: '',
                password: '',
                error: {
                    text: '',
                    shown: false
                }
            }
        },
        methods: {
            // 登陆事件
            login() {
                if (!this.username || !this.password) {
                    this.error.text = '用户名和密码不能为空'
                    this.error.shown = true
                    return;
                }
                this.$router.push('App')
            }
        },
        // 实例已完成以下的配置：数据观测(data observer)，属性和方法的运算， watch/event 事件回调
        created() {
            this.error.shown = false
            $('body').attr('class', 'login')
        },
        // 此时元素创建完成
        mounted() {
            $('input')[0].focus()
        }
    }
</script>
